Task 3.1.2 Spring Security
Sly-old-Fox/Task-3.1.2-Spring-Security- pull request #1
Opened 2024-10-06 18:35 UTC by 0uzel

2024-10-08 08:40 UTC, pdasilem requested changes

2024-10-08 08:40 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AuthenticationController.java
> +        user.setRoles(Collections.singleton(Role.ROLE_USER));
почему по умолчанию юзер? Нужен выбор ролей

2024-10-08 08:40 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/User.java
> +    @ElementCollection(targetClass = Role.class,fetch = FetchType.EAGER)
избавиться от игер

2024-10-08 08:40 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/Role.java
> +public enum Role implements GrantedAuthority {
сделай обычный ентити

2024-10-08 08:40 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AdminController.java
> +        if (bindingResult.hasErrors()) {
я не понимаю такого действия. объясни, плиз

2024-10-08 19:07 UTC, 0uzel commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/User.java
> +    @ElementCollection(targetClass = Role.class,fetch = FetchType.EAGER)
Исправил. Добавил @EntityGraph на метод поиска по username для аутентификации юзера

2024-10-08 19:15 UTC, 0uzel commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AdminController.java
> +        if (bindingResult.hasErrors()) {
Изначально я планировал сделать регистрацию для обычных пользователей( где по дефолту роль USER), а человек с ролью ADMIN мог бы сохранить пользователя и выбрать в процессе любую роль. Поэтому и было два метода для регистрации и для создания. Исправил: теперь только ADMIN может создавать/обновлять пользователей с выбором ролей

2024-10-08 19:22 UTC, 0uzel commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/Role.java
> +public enum Role implements GrantedAuthority {
исправил

2024-10-08 21:46 UTC, pdasilem requested changes

2024-10-08 21:46 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/repositories/UserRepository.java
> +    @EntityGraph(attributePaths = {"roles"})
использование энтитиграф сводит к нулю лэйзи загрузку.
но избавляет от н+1 )
другой вариант смотри

2024-10-09 10:04 UTC, 0uzel commented on src/main/java/ru/itmentor/spring/boot_security/demo/repositories/UserRepository.java
> +    @EntityGraph(attributePaths = {"roles"})
Поправил. Использовал @Query c JOIN  FETCH для метода аутентификации. Не стал использовать  Hibernate.initialize(), так как нет кэша второго уровня.

2024-10-09 10:18 UTC, pdasilem approved these changes

2024-10-09 10:37 UTC, merged